USE [master]
GO

/****** Object:  Database [ContactsDB]    Script Date: 08-07-2018 19:22:41 ******/
CREATE DATABASE [ContactsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EmployeeDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmployeeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EmployeeDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ContactsDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactsDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContactsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactsDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContactsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContactsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContactsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactsDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ContactsDB] SET  MULTI_USER 
GO

ALTER DATABASE [ContactsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactsDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ContactsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactsDB] SET  READ_WRITE 
GO


